[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "rustplay"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
log = "0.4.27"
web-sys = "0.3.77"
