name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust & wasm target
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli --force

      - name: Build WASM
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen target/wasm32-unknown-unknown/release/*.wasm \
            --target web --out-dir out --out-name app

      - name: Copy static files (index.html etc.)
        run: |
          cp index.html out/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
